
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: backend_container
    restart: always
    environment:
      PORT: 5000
      MONGO_URI: "mongodb://admin:password@mongodb:27017/"
      TOKEN_SECRET_KEY: "mkt"
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    

  frontend:
    build: ./client
    container_name: frontend_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  mongo_data: